# -*- coding: utf-8 -*-

# this changed with ImageLabel


from PyQt5 import QtCore, QtGui, QtWidgets
from imagelabel import ImageLabel

class Ui_PdfScanDialog(object):
    def setupUi(self, PdfScanDialog, lang):
        PdfScanDialog.setObjectName("PdfScanDialog")
        PdfScanDialog.resize(738, 601)
        self.vl_dialog = QtWidgets.QVBoxLayout(PdfScanDialog)
        self.vl_dialog.setObjectName("vl_dialog")
        self.top_widget = QtWidgets.QWidget(PdfScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_widget.sizePolicy().hasHeightForWidth())
        self.top_widget.setSizePolicy(sizePolicy)
        self.top_widget.setMinimumSize(QtCore.QSize(0, 42))
        self.top_widget.setStyleSheet("")
        self.top_widget.setObjectName("top_widget")
        self.hl_topwidget = QtWidgets.QHBoxLayout(self.top_widget)
        self.hl_topwidget.setContentsMargins(0, 0, 0, 0)
        self.hl_topwidget.setObjectName("hl_topwidget")
        self.bScan = QtWidgets.QToolButton(self.top_widget)
        self.bScan.setMinimumSize(QtCore.QSize(52, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/scanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bScan.setIcon(icon)
        self.bScan.setIconSize(QtCore.QSize(48, 19))
        self.bScan.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bScan.setAutoRaise(True)
        self.bScan.setObjectName("bScan")
        self.hl_topwidget.addWidget(self.bScan)
        self.bUp = QtWidgets.QToolButton(self.top_widget)
        self.bUp.setMinimumSize(QtCore.QSize(40, 40))
        self.bUp.setMaximumSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/move_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bUp.setIcon(icon1)
        self.bUp.setIconSize(QtCore.QSize(39, 23))
        self.bUp.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bUp.setAutoRaise(True)
        self.bUp.setObjectName("bUp")
        self.hl_topwidget.addWidget(self.bUp)
        self.bDown = QtWidgets.QToolButton(self.top_widget)
        self.bDown.setMinimumSize(QtCore.QSize(40, 40))
        self.bDown.setMaximumSize(QtCore.QSize(40, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/move_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDown.setIcon(icon2)
        self.bDown.setIconSize(QtCore.QSize(39, 23))
        self.bDown.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bDown.setAutoRaise(True)
        self.bDown.setObjectName("bDown")
        self.hl_topwidget.addWidget(self.bDown)
        self.bRotate = QtWidgets.QToolButton(self.top_widget)
        self.bRotate.setMinimumSize(QtCore.QSize(40, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRotate.setIcon(icon3)
        self.bRotate.setIconSize(QtCore.QSize(32, 32))
        self.bRotate.setAutoRaise(True)
        self.bRotate.setObjectName("bRotate")
        self.hl_topwidget.addWidget(self.bRotate)
        self.bCrop = QtWidgets.QToolButton(self.top_widget)
        self.bCrop.setMinimumSize(QtCore.QSize(40, 40))
        self.bCrop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCrop.setIcon(icon4)
        self.bCrop.setIconSize(QtCore.QSize(32, 32))
        self.bCrop.setAutoRaise(True)
        self.bCrop.setObjectName("bCrop")
        self.hl_topwidget.addWidget(self.bCrop)
        self.bDel = QtWidgets.QToolButton(self.top_widget)
        self.bDel.setMinimumSize(QtCore.QSize(40, 40))
        self.bDel.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDel.setIcon(icon7)
        self.bDel.setIconSize(QtCore.QSize(32, 32))
        self.bDel.setAutoRaise(True)
        self.bDel.setObjectName("bDel")
        self.hl_topwidget.addWidget(self.bDel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_topwidget.addItem(spacerItem)
        self.bSave = QtWidgets.QPushButton(self.top_widget)
        self.bSave.setMinimumSize(QtCore.QSize(0, 38))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSave.setIcon(icon5)
        self.bSave.setObjectName("bSave")
        self.hl_topwidget.addWidget(self.bSave)
        self.vl_dialog.addWidget(self.top_widget)
        self.main_widget = QtWidgets.QWidget(PdfScanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.hl_main = QtWidgets.QHBoxLayout(self.main_widget)
        self.hl_main.setContentsMargins(0, 0, 0, 0)
        self.hl_main.setSpacing(2)
        self.hl_main.setObjectName("hl_main")
        self.lw = QtWidgets.QListWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw.sizePolicy().hasHeightForWidth())
        self.lw.setSizePolicy(sizePolicy)
        self.lw.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lw.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lw.setMovement(QtWidgets.QListView.Static)
        self.lw.setDragEnabled(False)
        self.lw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.lw.setIconSize(QtCore.QSize(160, 160))
        self.lw.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lw.setGridSize(QtCore.QSize(160, 160))
        self.lw.setViewMode(QtWidgets.QListView.IconMode)
        self.lw.setSelectionRectVisible(False)
        self.lw.setObjectName("lw")
        self.hl_main.addWidget(self.lw)
        self.lPreview = ImageLabel(self.main_widget)
        self.lPreview.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored))
        self.lPreview.setText("")
        self.lPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.lPreview.setObjectName("lPreview")
        self.hl_main.addWidget(self.lPreview)
        self.vl_dialog.addWidget(self.main_widget)

        self.retranslateUi(PdfScanDialog, lang)
        QtCore.QMetaObject.connectSlotsByName(PdfScanDialog)

    def retranslateUi(self, PdfScanDialog, lang):
        PdfScanDialog.setWindowTitle(lang.tr("scanpdf"))
        self.bScan.setText("...")
        self.bUp.setText("...")
        self.bDown.setText("...")
        self.bRotate.setText("...")
        self.bSave.setText(lang.tr("save"))
import images_rc
