# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'previewdialoggui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreviewDialog(object):
    def setupUi(self, PreviewDialog, lang):
        PreviewDialog.setObjectName("PreviewDialog")
        PreviewDialog.resize(671, 654)
        self.vl_dialog = QtWidgets.QVBoxLayout(PreviewDialog)
        self.vl_dialog.setObjectName("vl_dialog")
        self.top_widget = QtWidgets.QWidget(PreviewDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_widget.sizePolicy().hasHeightForWidth())
        self.top_widget.setSizePolicy(sizePolicy)
        self.top_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.top_widget.setObjectName("top_widget")
        self.hl_top_widget = QtWidgets.QHBoxLayout(self.top_widget)
        self.hl_top_widget.setContentsMargins(0, 0, 0, 0)
        self.hl_top_widget.setObjectName("hl_top_widget")
        self.bRestore = QtWidgets.QToolButton(self.top_widget)
        self.bRestore.setMinimumSize(QtCore.QSize(40, 40))
        self.bRestore.setMaximumSize(QtCore.QSize(40, 40))
        self.bRestore.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRestore.setIcon(icon)
        self.bRestore.setIconSize(QtCore.QSize(33, 32))
        self.bRestore.setAutoRaise(True)
        self.bRestore.setObjectName("bRestore")
        self.hl_top_widget.addWidget(self.bRestore)
        self.bRotate = QtWidgets.QToolButton(self.top_widget)
        self.bRotate.setMinimumSize(QtCore.QSize(40, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRotate.setIcon(icon1)
        self.bRotate.setIconSize(QtCore.QSize(32, 32))
        self.bRotate.setAutoRaise(True)
        self.bRotate.setObjectName("bRotate")
        self.hl_top_widget.addWidget(self.bRotate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_top_widget.addItem(spacerItem)
        self.vl_dialog.addWidget(self.top_widget)
        self.gv = QtWidgets.QGraphicsView(PreviewDialog)
        self.gv.setObjectName("gv")
        self.vl_dialog.addWidget(self.gv)
        self.box = QtWidgets.QDialogButtonBox(PreviewDialog)
        self.box.setOrientation(QtCore.Qt.Horizontal)
        self.box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.box.setObjectName("box")
        self.vl_dialog.addWidget(self.box)

        self.retranslateUi(PreviewDialog, lang)
        self.box.accepted.connect(PreviewDialog.accept) # type: ignore
        self.box.rejected.connect(PreviewDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PreviewDialog)

    def retranslateUi(self, PreviewDialog, lang):
        PreviewDialog.setWindowTitle(lang.tr("viewcrop"))
        self.bRestore.setToolTip(lang.tr("restore"))
        self.bRotate.setText("...")
import images_rc
