# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialogui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog, lang):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(306, 122)
        self.vl_dialog = QtWidgets.QVBoxLayout(SettingsDialog)
        self.vl_dialog.setObjectName("vl_dialog")
        self.hl_papersize = QtWidgets.QHBoxLayout()
        self.hl_papersize.setObjectName("hl_papersize")
        self.lPaper = QtWidgets.QLabel(SettingsDialog)
        self.lPaper.setObjectName("lPaper")
        self.hl_papersize.addWidget(self.lPaper)
        self.cbPaperSize = QtWidgets.QComboBox(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPaperSize.sizePolicy().hasHeightForWidth())
        self.cbPaperSize.setSizePolicy(sizePolicy)
        self.cbPaperSize.setObjectName("cbPaperSize")
        self.hl_papersize.addWidget(self.cbPaperSize)
        self.vl_dialog.addLayout(self.hl_papersize)

        self.hl_lang = QtWidgets.QHBoxLayout()
        self.hl_lang.setObjectName("hl_lang")
        self.l_lang = QtWidgets.QLabel(SettingsDialog)
        self.l_lang.setObjectName("l_lang")
        self.hl_lang.addWidget(self.l_lang)
        self.cb_lang = QtWidgets.QComboBox(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_lang.sizePolicy().hasHeightForWidth())
        self.cb_lang.setSizePolicy(sizePolicy)
        self.cb_lang.setObjectName("cb_lang")
        self.hl_lang.addWidget(self.cb_lang)
        self.vl_dialog.addLayout(self.hl_lang)

        self.cbUpdateOnStart = QtWidgets.QCheckBox(SettingsDialog)
        self.cbUpdateOnStart.setObjectName("cbUpdateOnStart")
        self.vl_dialog.addWidget(self.cbUpdateOnStart)
        self.bbox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.bbox.setOrientation(QtCore.Qt.Horizontal)
        self.bbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbox.setObjectName("bbox")
        self.vl_dialog.addWidget(self.bbox)

        self.retranslateUi(SettingsDialog, lang)
        self.bbox.accepted.connect(SettingsDialog.accept) # type: ignore
        self.bbox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog, lang):
        SettingsDialog.setWindowTitle(lang.tr("settings"))
        self.lPaper.setText(lang.tr("pagesize"))
        self.cbUpdateOnStart.setText(lang.tr("updateonstart"))
        self.l_lang.setText(lang.tr("interfacelang"))
